# Generated by Django 5.2.17 on 2026-10-05 00:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("journeys", "0001_initial"),
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate_category",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("standard", "Standard"),
                            ("reduced", "Reduced"),
                            ("free", "Free"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("pending", "Pending human review"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "final_category",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("standard", "Standard"),
                            ("reduced", "Reduced"),
                            ("free", "Free"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("reviewer_reference", models.CharField(blank=True, max_length=100)),
                ("reason", models.TextField(blank=True)),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_decisions",
                        to="journeys.participantjourney",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_decisions",
                        to="participants.participant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
