# Generated by Django 5.2.17 on 2026-10-05 01:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grow_access', '0001_initial'),
        ('journeys', '0002_alter_participantjourney_resume_state'),
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessdecision',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='accessdecision',
            name='decision_chain_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='accessdecision',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='grow_access.accessdecision'),
        ),
        migrations.AddField(
            model_name='accessdecision',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='accessdecision',
            constraint=models.UniqueConstraint(fields=('decision_chain_id', 'version'), name='unique_access_decision_version'),
        ),
    ]
