# Generated by Django 5.2.17 on 2026-10-05 00:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("journeys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("self_report", "Self report"),
                            ("behavioural_story", "Behavioural story"),
                            ("structured_response", "Structured response"),
                            ("practical_task", "Practical task"),
                            ("reviewer_observation", "Reviewer observation"),
                            ("guardian_context", "Guardian context"),
                            ("follow_up", "Follow up"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("reference_kind", models.CharField(default="unknown", max_length=100)),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                ("provenance_version", models.CharField(default="foundation-v1", max_length=100)),
                ("occurred_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AssessmentSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("definition_code", models.CharField(default="unknown", max_length=100)),
                ("definition_version", models.CharField(default="unknown", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("draft", "Draft"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "sufficiency_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("sufficient", "Sufficient"),
                            ("insufficient", "Insufficient"),
                            ("review_required", "Review required"),
                            ("not_applicable", "Not applicable"),
                            ("unable_to_assess", "Unable to assess"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessment_sessions",
                        to="journeys.participantjourney",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Contradiction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("summary", models.TextField()),
                (
                    "resolution_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("accepted_uncertainty", "Accepted uncertainty"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("resolution", models.TextField(blank=True)),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contradictions",
                        to="journeys.participantjourney",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EvidenceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("evidence_chain_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("version", models.PositiveIntegerField(default=1)),
                ("dimension_code", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("personality", "Personality tendency"),
                            ("interest", "Interest"),
                            ("ability", "Current ability"),
                            ("potential", "Potential and learning speed"),
                            ("value", "Work value"),
                            ("environment", "Environment preference"),
                            ("constraint", "Constraint"),
                            ("behaviour", "Practical behaviour"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                (
                    "value_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("known", "Known"),
                            ("not_applicable", "Not applicable"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "numeric_value",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
                ),
                ("text_value", models.TextField(blank=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("supports", "Supports"),
                            ("conflicts", "Conflicts"),
                            ("neutral", "Neutral"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_band",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
                ),
                ("confidence_reason", models.TextField(blank=True)),
                (
                    "privacy_class",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("structured_evidence", "Structured guidance evidence"),
                            ("sensitive", "Sensitive"),
                        ],
                        default="structured_evidence",
                        max_length=30,
                    ),
                ),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "assessment_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_items",
                        to="assessments.assessmentsession",
                    ),
                ),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_items",
                        to="journeys.participantjourney",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="superseded_by",
                        to="assessments.evidenceitem",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_items",
                        to="assessments.evidencesource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContradictionEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("claim", "Claim"),
                            ("counterevidence", "Counterevidence"),
                            ("context", "Context"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                (
                    "contradiction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="assessments.contradiction"
                    ),
                ),
                (
                    "evidence_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="assessments.evidenceitem"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contradiction",
            name="evidence_items",
            field=models.ManyToManyField(
                through="assessments.ContradictionEvidence", to="assessments.evidenceitem"
            ),
        ),
        migrations.AddConstraint(
            model_name="contradictionevidence",
            constraint=models.UniqueConstraint(
                fields=("contradiction", "evidence_item"), name="unique_evidence_per_contradiction"
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceitem",
            constraint=models.UniqueConstraint(
                fields=("evidence_chain_id", "version"), name="unique_evidence_chain_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="evidenceitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("confidence_score__isnull", True),
                    models.Q(("confidence_score__gte", 0), ("confidence_score__lte", 1)),
                    _connector="OR",
                ),
                name="confidence_score_between_zero_and_one",
            ),
        ),
    ]
