# Generated by Django 5.2.17 on 2026-10-05 02:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('purpose', models.TextField()),
                ('validity_notice', models.TextField(default='Pilot engineering content; no psychometric or clinical validity claim.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentDimension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('cognitive_functional', 'Cognitive / functional'), ('personality_work_style', 'Personality / work style'), ('communication_social', 'Communication / social'), ('creativity', 'Creativity'), ('vocational_interest', 'Vocational interest'), ('work_value', 'Work value'), ('work_environment', 'Work environment')], max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('pilot_only', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=100)),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('purpose', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='audience',
            field=models.CharField(choices=[('general', 'General'), ('grade_8_10', 'Grade 8-10'), ('intermediate', 'Intermediate'), ('university', 'University'), ('graduate', 'Graduate'), ('adult_career_switcher', 'Adult career switcher')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='language',
            field=models.CharField(default='ur', max_length=10),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='locale',
            field=models.CharField(default='pk', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='maximum_items',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contradiction',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contradiction',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contradiction',
            name='reviewer_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contradiction',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='interpretation_method',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='interpretation_version',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='normalized_interpretation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='review_status',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected'), ('needs_clarification', 'Needs clarification')], default='unreviewed', max_length=30),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='structured_value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='supporting_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='assessmentsession',
            name='status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('draft', 'Draft'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('stopped_early', 'Stopped early'), ('cancelled', 'Cancelled')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='evidencesource',
            name='source_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('self_report', 'Self report'), ('structured_question', 'Structured question'), ('open_response', 'Open response'), ('practical_task', 'Practical task'), ('human_observation', 'Human observation'), ('behavioural_signal', 'Behavioural signal'), ('historical_example', 'Historical example'), ('follow_up', 'Follow up'), ('reviewer_judgment', 'Reviewer judgment'), ('behavioural_story', 'Behavioural story (legacy)'), ('structured_response', 'Structured response (legacy)'), ('reviewer_observation', 'Reviewer observation (legacy)'), ('guardian_context', 'Guardian context (legacy)')], default='unknown', max_length=40),
        ),
        migrations.AddField(
            model_name='contradiction',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contradictions', to='assessments.assessmentdimension'),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence_items', to='assessments.assessmentdimension'),
        ),
        migrations.CreateModel(
            name='AssessmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=100)),
                ('item_type', models.CharField(choices=[('likert', 'Likert'), ('binary', 'Binary'), ('single_choice', 'Single choice'), ('multi_choice', 'Multiple choice'), ('ranking', 'Ranking'), ('numeric', 'Numeric'), ('short_text', 'Short text'), ('long_text', 'Long text'), ('scenario_choice', 'Scenario choice')], max_length=30)),
                ('purpose', models.CharField(choices=[('core', 'Core evidence'), ('clarification', 'Contradiction clarification'), ('open_discovery', 'Open discovery')], default='core', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('response_schema', models.JSONField(blank=True, default=dict)),
                ('interpretation_rules', models.JSONField(blank=True, default=dict)),
                ('evidence_source_type', models.CharField(default='structured_question', max_length=40)),
                ('pilot_only', models.BooleanField(default=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='assessments.assessmentdimension')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='assessments.assessmentsection')),
            ],
            options={
                'ordering': ['section__order', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentItemVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant_version', models.PositiveIntegerField(default=1)),
                ('language', models.CharField(max_length=10)),
                ('locale', models.CharField(default='pk', max_length=20)),
                ('audience', models.CharField(choices=[('general', 'General'), ('grade_8_10', 'Grade 8-10'), ('intermediate', 'Intermediate'), ('university', 'University'), ('graduate', 'Graduate'), ('adult_career_switcher', 'Adult career switcher')], default='general', max_length=30)),
                ('education_stage', models.CharField(choices=[('unknown', 'Unknown'), ('grade_8', 'Grade 8'), ('grade_10', 'Grade 10'), ('intermediate', 'Intermediate or equivalent'), ('university', 'University'), ('graduate', 'Graduate'), ('other', 'Other')], default='unknown', max_length=20)),
                ('prompt', models.TextField()),
                ('helper_text', models.TextField(blank=True)),
                ('answer_labels', models.JSONField(blank=True, default=dict)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('content_status', models.CharField(choices=[('draft', 'Draft'), ('synthetic_pilot', 'Synthetic pilot'), ('human_reviewed_pilot', 'Human-reviewed pilot')], default='synthetic_pilot', max_length=30)),
                ('provenance', models.CharField(default='synthetic-pilot-authoring', max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='assessments.assessmentitem')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentItemPresentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('selection_status', models.CharField(max_length=40)),
                ('selection_reason', models.TextField()),
                ('selection_policy_version', models.CharField(max_length=100)),
                ('presented_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.assessmentitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='assessments.assessmentsession')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.assessmentitemvariant')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('structured_value', models.JSONField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True)),
                ('skipped', models.BooleanField(default=False)),
                ('completion_quality', models.CharField(default='unknown', max_length=20)),
                ('responded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('presentation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='response', to='assessments.assessmentitempresentation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentObservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observer_type', models.CharField(max_length=40)),
                ('observer_reference', models.CharField(blank=True, max_length=100)),
                ('structured_value', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.assessmentdimension')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='assessments.assessmentsession')),
                ('response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='assessments.assessmentresponse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('lifecycle', models.CharField(choices=[('draft', 'Draft'), ('pilot', 'Pilot only'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('selection_policy_version', models.CharField(default='deterministic-pilot-v1', max_length=100)),
                ('calculation_version', models.CharField(default='deterministic-pilot-v1', max_length=100)),
                ('maximum_items', models.PositiveSmallIntegerField(default=20)),
                ('limitations', models.TextField(default='Synthetic pilot content; not validated for participant guidance.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='assessments.assessmentdefinition')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentsection',
            name='assessment_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='assessments.assessmentversion'),
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='assessment_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='assessments.assessmentversion'),
        ),
        migrations.CreateModel(
            name='AssessmentDimensionRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('minimum_independent_sources', models.PositiveSmallIntegerField(default=2)),
                ('minimum_source_types', models.PositiveSmallIntegerField(default=2)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='version_requirements', to='assessments.assessmentdimension')),
                ('assessment_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dimension_requirements', to='assessments.assessmentversion')),
            ],
            options={
                'ordering': ['priority', 'dimension__code'],
            },
        ),
        migrations.AddField(
            model_name='assessmentsession',
            name='assessment_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='assessments.assessmentversion'),
        ),
        migrations.CreateModel(
            name='DimensionEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('independent_source_key', models.CharField(max_length=200)),
                ('eligible_for_aggregation', models.BooleanField(default=True)),
                ('eligibility_reason', models.TextField(blank=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dimension_evidence', to='assessments.assessmentdimension')),
                ('evidence_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='dimension_evidence_link', to='assessments.evidenceitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_evidence', to='assessments.assessmentsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DimensionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_chain_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('version', models.PositiveIntegerField(default=1)),
                ('sufficiency', models.CharField(choices=[('unknown', 'Unknown'), ('insufficient', 'Insufficient'), ('tentative', 'Tentative'), ('supported', 'Supported'), ('contradictory', 'Contradictory')], default='unknown', max_length=30)),
                ('confidence_band', models.CharField(choices=[('unknown', 'Unknown'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='unknown', max_length=20)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('supporting_count', models.PositiveSmallIntegerField(default=0)),
                ('conflicting_count', models.PositiveSmallIntegerField(default=0)),
                ('independent_source_count', models.PositiveSmallIntegerField(default=0)),
                ('source_type_count', models.PositiveSmallIntegerField(default=0)),
                ('unresolved_contradiction_count', models.PositiveSmallIntegerField(default=0)),
                ('calculation_version', models.CharField(max_length=100)),
                ('calculation_inputs', models.JSONField(default=dict)),
                ('reasons', models.JSONField(default=list)),
                ('next_action', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='assessments.assessmentdimension')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_results', to='assessments.assessmentsession')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='assessments.dimensionresult')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assessmentitemvariant',
            constraint=models.UniqueConstraint(fields=('item', 'variant_version', 'language', 'locale', 'audience', 'education_stage'), name='unique_item_content_variant'),
        ),
        migrations.AddConstraint(
            model_name='assessmentitempresentation',
            constraint=models.UniqueConstraint(fields=('session', 'item'), name='unique_presented_item_per_session'),
        ),
        migrations.AddConstraint(
            model_name='assessmentitempresentation',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='unique_presentation_sequence_per_session'),
        ),
        migrations.AddConstraint(
            model_name='assessmentversion',
            constraint=models.UniqueConstraint(fields=('definition', 'version'), name='unique_assessment_definition_version'),
        ),
        migrations.AddConstraint(
            model_name='assessmentversion',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_items__gte', 1)), name='assessment_maximum_items_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsection',
            constraint=models.UniqueConstraint(fields=('assessment_version', 'code'), name='unique_section_code_per_version'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsection',
            constraint=models.UniqueConstraint(fields=('assessment_version', 'order'), name='unique_section_order_per_version'),
        ),
        migrations.AddConstraint(
            model_name='assessmentitem',
            constraint=models.UniqueConstraint(fields=('assessment_version', 'code'), name='unique_item_code_per_version'),
        ),
        migrations.AddConstraint(
            model_name='assessmentdimensionrequirement',
            constraint=models.UniqueConstraint(fields=('assessment_version', 'dimension'), name='unique_dimension_requirement_per_version'),
        ),
        migrations.AddConstraint(
            model_name='assessmentdimensionrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_independent_sources__gte', 1)), name='minimum_independent_sources_positive'),
        ),
        migrations.AddConstraint(
            model_name='assessmentdimensionrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_source_types__gte', 1)), name='minimum_source_types_positive'),
        ),
        migrations.AddConstraint(
            model_name='dimensionresult',
            constraint=models.UniqueConstraint(fields=('result_chain_id', 'version'), name='unique_dimension_result_version'),
        ),
        migrations.AddConstraint(
            model_name='dimensionresult',
            constraint=models.CheckConstraint(condition=models.Q(('confidence_score__isnull', True), models.Q(('confidence_score__gte', 0), ('confidence_score__lte', 1)), _connector='OR'), name='dimension_confidence_score_between_zero_and_one'),
        ),
    ]
