# Generated by Django 5.2.17 on 2026-10-05 00:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("actor_type", models.CharField(max_length=50)),
                ("actor_reference", models.CharField(blank=True, max_length=100)),
                ("target_type", models.CharField(db_index=True, max_length=100)),
                ("target_id", models.UUIDField(db_index=True)),
                ("reason", models.TextField(blank=True)),
                ("correlation_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["occurred_at", "id"],
            },
        ),
    ]
