# Generated by Django 5.2.17 on 2026-10-05 00:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("closed", "Closed"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "life_stage_track",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("school", "School discovery"),
                            ("college", "College direction"),
                            ("university", "University and graduation direction"),
                            ("career_reset", "Career reset"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("preferred_language", models.CharField(default="unknown", max_length=20)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GuardianRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("guardian_reference_digest", models.CharField(blank=True, max_length=64)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("parent", "Parent"),
                            ("guardian", "Guardian"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "handling_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("required", "Required"),
                            ("acknowledged", "Acknowledged for development workflow"),
                            ("not_required", "Not required"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("policy_version", models.CharField(default="unknown", max_length=100)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_relationships",
                        to="participants.participant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("participation", "Participation"),
                            ("data_processing", "Data processing"),
                            ("research", "Research"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("pending", "Pending"),
                            ("granted", "Granted"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("policy_version", models.CharField(max_length=100)),
                ("actor_type", models.CharField(default="unknown", max_length=30)),
                ("actor_reference", models.CharField(blank=True, max_length=100)),
                (
                    "recorded_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("evidence_reference", models.CharField(blank=True, max_length=255)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_records",
                        to="participants.participant",
                    ),
                ),
            ],
            options={
                "ordering": ["recorded_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ParticipantProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "age_status",
                    models.CharField(
                        choices=[("unknown", "Unknown"), ("known", "Known")],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("age_years", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "minor_status",
                    models.CharField(
                        choices=[("unknown", "Unknown"), ("minor", "Minor"), ("adult", "Adult")],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "guardian_requirement",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("required", "Guardian handling required"),
                            ("not_required", "Guardian handling not required"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "education_stage",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("grade_8", "Grade 8"),
                            ("grade_10", "Grade 10"),
                            ("intermediate", "Intermediate or equivalent"),
                            ("university", "University"),
                            ("graduate", "Graduate"),
                            ("other", "Other"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("current_status", models.CharField(blank=True, max_length=100)),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="participants.participant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReferralSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("self", "Self"),
                            ("participant", "Participant referral"),
                            ("teacher", "Teacher"),
                            ("institution", "Institution"),
                            ("community", "Community"),
                            ("social", "Social media"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("source_code", models.CharField(blank=True, max_length=100)),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_source",
                        to="participants.participant",
                    ),
                ),
                (
                    "referring_participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals_made",
                        to="participants.participant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ParticipantIdentifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("internal_alias", "Internal alias"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("lookup_digest", models.CharField(blank=True, db_index=True, max_length=64)),
                ("ciphertext", models.TextField(blank=True)),
                ("key_version", models.CharField(blank=True, max_length=50)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identifiers",
                        to="participants.participant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("lookup_digest", ""), _negated=True),
                        fields=("identifier_type", "lookup_digest"),
                        name="unique_nonempty_identifier_digest",
                    )
                ],
            },
        ),
    ]
