# Generated by Django 5.2.17 on 2026-10-05 00:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipantJourney",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "track",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("school", "School discovery"),
                            ("college", "College direction"),
                            ("university", "University and graduation direction"),
                            ("career_reset", "Career reset"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                (
                    "current_state",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("consent_pending", "Consent pending"),
                            ("profile_incomplete", "Profile incomplete"),
                            ("discovery_in_progress", "Discovery in progress"),
                            ("assessment_in_progress", "Assessment in progress"),
                            ("experiment_pending", "Experiment pending"),
                            ("experiment_submitted", "Experiment submitted"),
                            ("human_review_required", "Human review required"),
                            ("recommendation_ready", "Recommendation-ready gate"),
                            ("roadmap_active", "Roadmap active"),
                            ("follow_up_due", "Follow-up due"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("opted_out", "Opted out"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=40,
                    ),
                ),
                (
                    "resume_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "New"),
                            ("consent_pending", "Consent pending"),
                            ("profile_incomplete", "Profile incomplete"),
                            ("discovery_in_progress", "Discovery in progress"),
                            ("assessment_in_progress", "Assessment in progress"),
                            ("experiment_pending", "Experiment pending"),
                            ("experiment_submitted", "Experiment submitted"),
                            ("human_review_required", "Human review required"),
                            ("recommendation_ready", "Recommendation-ready gate"),
                            ("roadmap_active", "Roadmap active"),
                            ("follow_up_due", "Follow-up due"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("opted_out", "Opted out"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                ("state_version", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journeys",
                        to="participants.participant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StateTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "from_state",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("consent_pending", "Consent pending"),
                            ("profile_incomplete", "Profile incomplete"),
                            ("discovery_in_progress", "Discovery in progress"),
                            ("assessment_in_progress", "Assessment in progress"),
                            ("experiment_pending", "Experiment pending"),
                            ("experiment_submitted", "Experiment submitted"),
                            ("human_review_required", "Human review required"),
                            ("recommendation_ready", "Recommendation-ready gate"),
                            ("roadmap_active", "Roadmap active"),
                            ("follow_up_due", "Follow-up due"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("opted_out", "Opted out"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("consent_pending", "Consent pending"),
                            ("profile_incomplete", "Profile incomplete"),
                            ("discovery_in_progress", "Discovery in progress"),
                            ("assessment_in_progress", "Assessment in progress"),
                            ("experiment_pending", "Experiment pending"),
                            ("experiment_submitted", "Experiment submitted"),
                            ("human_review_required", "Human review required"),
                            ("recommendation_ready", "Recommendation-ready gate"),
                            ("roadmap_active", "Roadmap active"),
                            ("follow_up_due", "Follow-up due"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("opted_out", "Opted out"),
                        ],
                        max_length=40,
                    ),
                ),
                ("command", models.CharField(max_length=100)),
                ("reason", models.TextField()),
                ("actor_type", models.CharField(max_length=30)),
                ("actor_reference", models.CharField(blank=True, max_length=100)),
                ("policy_version", models.CharField(default="foundation-v1", max_length=100)),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
                ("state_version_from", models.PositiveIntegerField()),
                ("state_version_to", models.PositiveIntegerField()),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="journeys.participantjourney",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="participantjourney",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("participant",),
                name="one_active_journey_per_participant",
            ),
        ),
    ]
