# Generated by Django 5.2.17 on 2026-10-05 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantjourney',
            name='resume_state',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('consent_pending', 'Consent pending'), ('profile_incomplete', 'Profile incomplete'), ('discovery_in_progress', 'Discovery in progress'), ('assessment_in_progress', 'Assessment in progress'), ('experiment_pending', 'Experiment pending'), ('experiment_submitted', 'Experiment submitted'), ('human_review_required', 'Human review required'), ('recommendation_ready', 'Recommendation-ready gate'), ('roadmap_active', 'Roadmap active'), ('follow_up_due', 'Follow-up due'), ('completed', 'Completed'), ('paused', 'Paused'), ('opted_out', 'Opted out')], default='', max_length=40),
        ),
    ]
