# Generated by Django 5.2.17 on 2026-10-05 00:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("journeys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("seven_day", "Seven day"),
                            ("thirty_day", "Thirty day"),
                            ("custom", "Custom"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("planned", "Planned"),
                            ("due", "Due"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outcome_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("action_attempted", "Action attempted"),
                            ("action_completed", "Action completed"),
                            ("not_completed", "Not completed"),
                            ("unable_to_assess", "Unable to assess"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="journeys.participantjourney",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
