# Generated by Django 5.2.17 on 2026-10-05 00:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("journeys", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HumanReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("minor_handling", "Minor handling"),
                            ("evidence_contradiction", "Evidence contradiction"),
                            ("access", "Access"),
                            ("foundation", "Foundation workflow"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("required", "Required"),
                            ("in_progress", "In progress"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("more_information", "More information required"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("reviewer_reference", models.CharField(blank=True, max_length=100)),
                ("summary", models.TextField(blank=True)),
                ("decision", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="human_reviews",
                        to="journeys.participantjourney",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HumanOverride",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("target_type", models.CharField(max_length=100)),
                ("target_id", models.UUIDField()),
                ("original_result", models.JSONField()),
                ("new_result", models.JSONField()),
                ("reviewer_reference", models.CharField(max_length=100)),
                ("reason", models.TextField()),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="overrides",
                        to="reviews.humanreview",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
