# Generated by Django 5.2.17 on 2026-10-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanreview',
            name='review_type',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('minor_handling', 'Minor handling'), ('evidence_contradiction', 'Evidence contradiction'), ('assessment_evidence', 'Assessment evidence'), ('access', 'Access'), ('foundation', 'Foundation workflow')], default='unknown', max_length=30),
        ),
    ]
